blueprint:
  name: Z-WaveJS swtich
  description: Automation blueprint for Z-Wave switches that support scene selection
    from an up/down button and multiple key press gestures
  domain: automation
  input:
    zwavejs_device:
      name: Z-Wave JS switch
      description: Select the sensor device which offers scene selection.
        Listed devices are not guaranteed to work with any/all of these button mappings.
      selector:
        device:
          integration: zwave_js
          entity:
            domain: sensor
    key_up:
      name: Key Up/On press 1x
      description: Action to run, when the button is pressed one time.
      default: []
      selector:
        action: {}
    key_down:
      name: Key Down/Off press 1x
      description: Action to run, when the button is pressed one time.
      default: []
      selector:
        action: {}
    key_up_held:
      name: Key Up/On held down
      description: Action to run, when the button is held down.
      default: []
      selector:
        action: {}
    key_down_held:
      name: Key Down/Off held down
      description: Action to run, when the button is held down.
      default: []
      selector:
        action: {}
    key_up_released:
      name: Key Up/On released
      description: Action to run, when the button is released.
      default: []
      selector:
        action: {}
    key_down_released:
      name: Key Down/Off released
      description: Action to run, when the button is released.
      default: []
      selector:
        action: {}
    key_up_2x:
      name: Key Up/On press 2x
      description: Action to run, when the button is pressed two times.
      default: []
      selector:
        action: {}
    key_down_2x:
      name: Key Down/Off press 2x
      description: Action to run, when the button is pressed two times.
      default: []
      selector:
        action: {}
    key_up_3x:
      name: Key Up/On press 3x
      description: Action to run, when the button is pressed three times.
      default: []
      selector:
        action: {}
    key_down_3x:
      name: Key Down/Off press 3x
      description: Action to run, when the button is pressed three times.
      default: []
      selector:
        action: {}
    key_up_4x:
      name: Key Up/On press 4x
      description: Action to run, when the button is pressed four times.
      default: []
      selector:
        action: {}
    key_down_4x:
      name: Key Down/Off press 4x
      description: Action to run, when the button is pressed four times.
      default: []
      selector:
        action: {}
    key_up_5x:
      name: Key Up/On press 5x
      description: Action to run, when the button is pressed five times.
      default: []
      selector:
        action: {}
    key_down_5x:
      name: Key Down/Off press 5x
      description: Action to run, when the button is pressed five times.
      default: []
      selector:
        action: {}
mode: single
max_exceeded: silent
variables:
  zwavejs_device: !input 'zwavejs_device'
trigger:
- platform: event
  event_type: zwave_js_event
condition: '{{ trigger.event.data.device_id == (zwavejs_device | string) and trigger.event.data.command_class == 91 }}'
action:
- variables:
    scene_id: '{{ (trigger.event.data.property_key_name | int) }}' # values 001,002 and sometimes 003
    event: '{{ trigger.event.data.value }}'
- choose:
  - conditions: '{{ scene_id == 2 and event == "KeyPressed" }}'
    sequence: !input 'key_up'
  - conditions: '{{ scene_id == 1 and event == "KeyPressed" }}'
    sequence: !input 'key_down'
  - conditions: '{{ scene_id == 2 and event == "KeyReleased" }}'
    sequence: !input 'key_up_released'
  - conditions: '{{ scene_id == 1 and event == "KeyReleased" }}'
    sequence: !input 'key_down_released'
  - conditions: '{{ scene_id == 2 and event == "KeyHeldDown" }}'
    sequence: !input 'key_up_held'
  - conditions: '{{ scene_id == 1 and event == "KeyHeldDown" }}'
    sequence: !input 'key_down_held'
  - conditions: '{{ scene_id == 2 and event == "KeyPressed2x" }}'
    sequence: !input 'key_up_2x'
  - conditions: '{{ scene_id == 1 and event == "KeyPressed2x" }}'
    sequence: !input 'key_down_2x'
  - conditions: '{{ scene_id == 2 and event == "KeyPressed3x" }}'
    sequence: !input 'key_up_3x'
  - conditions: '{{ scene_id == 1 and event == "KeyPressed3x" }}'
    sequence: !input 'key_down_3x'
  - conditions: '{{ scene_id == 2 and event == "KeyPressed4x" }}'
    sequence: !input 'key_up_4x'
  - conditions: '{{ scene_id == 1 and event == "KeyPressed4x" }}'
    sequence: !input 'key_down_4x'
  - conditions: '{{ scene_id == 2 and event == "KeyPressed5x" }}'
    sequence: !input 'key_up_5x'
  - conditions: '{{ scene_id == 1 and event == "KeyPressed5x" }}'
    sequence: !input 'key_down_5x'
